baseURL: https://rstudioanalysis.netlify.app/
title: RStudio Analysis
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
params:
  author: Marko Šenk
  description: Marko Šenk
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/gohugoio
    - icon: twitter
      name: Twitter
      url: https://twitter.com/gohugoio
